CREATE TABLE `orders`  (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `collection_id` bigint NOT NULL,
  `order_type` tinyint NOT NULL DEFAULT 0 COMMENT '0: list, 1: bid',
  `order_item_size` int NOT NULL DEFAULT 1,
  `remaining_item_size` int NOT NULL DEFAULT 1,
  `order_hash` varchar(72) NOT NULL,
  `token_address` varchar(64) NOT NULL,
  `max_price` decimal(15, 5) NOT NULL,
  `min_price` decimal(15, 5) NOT NULL,
  `expected_price` decimal(15, 5) NOT NULL,
  `order_state` tinyint NOT NULL DEFAULT 0 COMMENT '0: create, 1: matched,-1: cancel, -2: expired',
  `order_start_time` bigint NOT NULL,
  `order_end_time` bigint NOT NULL,
  `detail` json NOT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniq_order_hash`(`hash`) USING BTREE
);

CREATE TABLE `transactions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `collection_id` bigint NOT NULL,
  `token_address` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `maker_hash` json NOT NULL,
  `taker_hash` json NOT NULL,
  `gas_tx_hash` varchar(72) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `gas_price` decimal(15,5) DEFAULT NULL,
  `maker_offer` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `taker_offer` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `maker` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `taker` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `fill_order_detail` json NOT NULL,
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '0: create, 1: start prepare, 2: prepare success, 3: matched, -1: failed',
  `request_id` varchar(128) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `prepare_tx_hash` varchar(72) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `match_tx_hash` varchar(72) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `price` decimal(15,5) DEFAULT NULL,
  `numerator` int DEFAULT NULL,
  `denominator` int DEFAULT NULL,
  `item_numerator` int DEFAULT NULL,
  `item_denominator` int DEFAULT NULL,
  `item_size` int DEFAULT NULL,
  `match_block_number` bigint DEFAULT NULL,
  `match_timestamp` bigint DEFAULT NULL,
  `failed_reason` text COLLATE utf8mb4_general_ci,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_transactions_status` (`status`) USING BTREE,
  KEY `fk_transactions_collection_id` (`collection_id`),
  KEY `idx_transactions_token_address` (`token_address`) USING BTREE,
  KEY `idx_transactions_maker` (`maker`) USING BTREE,
  KEY `idx_transactions_taker` (`taker`) USING BTREE,
  CONSTRAINT `fk_transactions_collection_id` FOREIGN KEY (`collection_id`) REFERENCES `collections` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);